### PR TITLE
Update action_or_description.md

### PR DESCRIPTION
**Pull request by brianteeman**
cosmetic change to force new lines

### CODE REVIEW

**Comment by HLeithner** [comment]
Not sure why + is better then - and not * is used.
Other question do you use an editor or why are 2 spaces ended to list items, this line break will not be rendered at least not on docusaurus.

**Comment by brianteeman** [comment]
The double space is what the GitHub markdown docs says to do for a new line

**Comment by HLeithner** [comment]
> The double space is what the GitHub markdown docs says to do for a new line

yes I know but is implicit for list elements

**Comment by brianteeman** [comment]
I dont remember why I wrote those parts as new lines and not lists. I just did this pr to make sure they rendered as new lines.

**Comment by brianteeman** [comment]
see #140

**Pull request closed without merging**
