### PR TITLE
Improve structure of chapter Building extensions

### PR DESCRIPTION
**Pull request by chmst**
The documentation für building extensions is still nearly empty but also not consistent. This PR tries to fix that and adds a few elements 

grafik

### CODE REVIEW

**Comment by chmst** [comment]
Could not find how to order items in deeper structure - see plugins

**Comment by HLeithner** [comment]
you need to add sidebar_position to the top of the document if we talk about the same order 
```
---
sidebar_position: 999
---
```

**Comment by chmst** [comment]
thanks. 

Another question: 
I renamed some elements to make the structure consistent (plural/singular). This causes a 404 in the main page ( the link goes to component, not components.
How can I fix that?

**Comment by HLeithner** [comment]
> thanks.
> 
> @HLeithner Another question: I renamed some elements to make the structure consistent (plural/singular). This causes a 404 in the main page ( the link goes to component, not components. How can I fix that?

then you have to change this link too

**Comment by HLeithner** [comment]
This section have changed already I'm closing this pr, thanks

**Pull request closed without merging**
