### PR TITLE
Update icons.md

### PR DESCRIPTION
**Pull request by chmst**
### **User description**
Improve accessibility

___

### **PR Type**
documentation

___

### **Description**
- Added `aria-hidden="true"` attribute to icon spans to improve accessibility.
- Ensured icons are hidden from screen readers, enhancing user experience for visually impaired users.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Documentation</strong></td><td><table>
<tr>
  <td>
    <details>
      <summary><strong>icons.md</strong><dd><code>Enhance icon accessibility with aria-hidden attribute</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>

versioned_docs/version-5.2/general-concepts/icons.md

<li>Added <code>aria-hidden="true"</code> attribute to icon spans.<br> <li> Improved accessibility by hiding icons from screen readers.<br>

</details>

  </td>
  <td><a href="https://github.com/joomla/Manual/pull/324/files#diff-0ea40f30af9c44975e970c4ef29d4f2d1c6c7964c9749a22eda650e3ac56097a">+4/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    
</table></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**: Comment `/help "your question"` on any pull request to receive relevant information

### CODE REVIEW

**Comment by HLeithner** [comment]
please add this also to the current documentation in `/docs` thanks

**Comment by chmst** [comment]
Docs changed. https://docs.joomla.org/J4.x:Joomla_Standard_Font_Awesome_Fonts

**Comment by HLeithner** [comment]
sorry that was an misunderstanding what I mean was please also update the upcoming documentation https://github.com/joomla/Manual/blob/main/docs/general-concepts/icons.md

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
