### PR TITLE
Implementing categories in a component

### PR DESCRIPTION
**Pull request by robbiejackson**
The github dev didn't give me the option of creating a new branch when I was saving the edits, but only offered me the fix-filenames branch I was using for the last change. 

Also this section is very long. I'll probably split it up, but I wanted to get it all down and see how it looked.

### CODE REVIEW

**Comment by HLeithner** [comment]
if you have code block you have to add 3 \` characters + the programming language at the beginning on it's own line and again 3 \` on it's own line after the coding block

**Comment by robbiejackson** [comment]
is there an example somewhere of the code blocks?

**Comment by HLeithner** [comment]
I will fix yours

**Comment by chmst** [comment]
@robbiejackson Example here: https://github.com/joomla/Manual/blob/main/docs/using-core-functions/dashboard.md?plain=1#L6

The xml-title is displayed as a headline above the code.

**Comment by HLeithner** [comment]
merging for now

**Pull request merged**
