### PR TITLE
Table columns

### PR DESCRIPTION
**Pull request by brianteeman**
How to add the user-defined table columns script to your component

### CODE REVIEW

**Comment by chmst** [comment]
Like this. But as I know users, they stop reading before the #note. You could write the requirements at the beginning.

**Comment by brianteeman** [comment]
I like to assume that people will be following the advice elsewhere on how to build a component before they get to this - so they should already have a valid table with table headers.

The note is for the exceptions when developers want to break the UI and still expect some of the features of the UI.

In summary - it's fine where it is

**Comment by HLeithner** [comment]
I think the description isn't good but better then nothing

**Comment by HLeithner** [comment]
thanks

**Comment by brianteeman** [comment]
> I think the description isn't good but better then nothing

by all means improve it

**Pull request merged**
