### PR TITLE
Update webservices.md with added security

### PR DESCRIPTION
**Pull request by alexandreelise**
Hi @pe7er,
Thanks for the shoutout, no offense to your code. You were the first to make an example and that's great for the Joomla community. We need more volunteers like you spreading the Joomla love and try contributing as much as they can at the their own pace even if it is a one character typo. Just wanted to add what I feel would be a little bit more secure and up-to-date. For example using HTTP/2 over TLS rather than HTTP 1.1. I know there is HTTP/3 but it is not yet widely spread as HTTP/2 is. Since it's a tutorial that potentially many people would see it would be great to use the latest and greatest as much as possible. Thanks again my Super Joomler friend.

### CODE REVIEW

**Comment by HLeithner** [comment]
Saving secrets in environment variables is also not the best idea. I thinks it's better to add a comment to store it as a secure place then suggesting a less understandable way (understand was $_SERVER means).

https://www.trendmicro.com/en_us/research/22/h/analyzing-hidden-danger-of-environment-variables-for-keeping-secrets.html

**Comment by alexandreelise** [comment]
Hi Harald, Good point.Thanks for your suggestion. In fact I know that Env vars is less than ideal and that a comment to tell people  to save the token in safe might be easier to understand that's why more expérienced in web app security people like you are there to strive for the best pratice without leaving out the user friendly aspect. like you said before just adding a comment is easier and even safer. Thanks again Super Joomler.

**Comment by alexandreelise** [comment]
Hi @HLeithner there is a build error due to the same issue you found here in docker for linux repo https://github.com/docker/for-linux/issues/599#issuecomment-491851269

**Comment by HLeithner** [comment]
> Hi @HLeithner there is a build error due to the same issue you found here in docker for linux repo [docker/for-linux#599 (comment)](https://github.com/docker/for-linux/issues/599#issuecomment-491851269)

Nice that you found my own comment on this topic ;) but it's different.

**Comment by alexandreelise** [comment]
Hi @HLeithner I'm willing to learn from someone more knowledgeable on the subject. Someone like you. To improve my skills learn even more cool stuff.

**Comment by HLeithner** [comment]
@alexandreelise something is broken in this PR
@pe7er can you please coordinate with @alexandreelise on this PR and your own #41 please?

**Comment by alexandreelise** [comment]
Hi @HLeithner is there any issue with this PR?

**Comment by HLeithner** [comment]
sorry I missed this pr, I merged it for now if something is missing we can fix it later.

**Comment by alexandreelise** [comment]
Just wanted to make sure everything was as expected and required by the maintainers. Thanks again. Have a great weekend.

**Pull request merged**
