### PR TITLE
Added Database: select, insert, update, delete

### PR DESCRIPTION
**Pull request by pe7er**
I've converted
https://docs.joomla.org/J4.x:Selecting_data_using_JDatabase
to markdown documents:
- select data
- query results

and
https://docs.joomla.org/J4.x:Inserting_Updating_and_Removing_data_using_JDatabase
to
- insert data
- update data
- delete data

PS: it was not possible to add a yellow background to a markdown table. So I've added the tables in HTML instead.

### CODE REVIEW

**Comment by HLeithner** [comment]
Did a local compile work?

**Comment by pe7er** [comment]
I have not tried that. 
I just used PHPStorm with it's MD result view to  the created documents.

**Comment by HLeithner** [comment]
> I have not tried that. I just used PHPStorm with it's MD result view to the created documents.

OK, phpstorm thinks that this is a markdown file but actually it's a MDX file and gets preprocessed.

Can you fix it? In the readme is a short introduction.

**Comment by HLeithner** [comment]
I fixed it in the pull/225/head branch... (failed to push directly into your branch) I will do this later.

**Comment by HLeithner** [comment]
I updated the styling and fixed some errors. should be ok now.

**Pull request merged**
