### PR TITLE
Create new features page for 5.1

### PR DESCRIPTION
**Pull request by LadySolveig**
- Implementation of JoomlaDialog script

### CODE REVIEW

**Comment by HLeithner** [comment]
would you please create all 4 pages

New features
New deprecations (already exists)
Removed and backward incompatibility
Compatibility Plugin

**Comment by HLeithner** [comment]
is the last commit a copy from the 5.0 migration page? because of all the classes in it.

**Comment by LadySolveig** [comment]
I copied the compat-plugin page 1:1 - I was unsure whether anything would change here and thought I'd leave it as general information for 5.1 as well? I can of course delete the content.

**Comment by HLeithner** [comment]
on this page is only the information between 5.0 and 5.1

**Comment by LadySolveig** [comment]
Ok, makes sense - I just left the general explanation in there and a link to the 5.0 version for now. Hope that fits.

**Pull request merged**
