### PR TITLE
"style guide" is misleading in the context of documentation. It is a …

### PR DESCRIPTION
**Pull request by chmst**
…link to coding standards and code style

### CODE REVIEW

**Comment by brianteeman** [comment]
agreed 

personaly I would put this link with the other 4 main blocks

and replace it (if necessary) to a page that is a style guide for writing documentation

**Comment by chmst** [comment]
> style guide for writing documentation

work in progress @crystalenka

**Comment by crystalenka** [comment]
Just leaving this here so I can find it again; these are a couple light guiding principles that I'm starting with.

1. Refer to people as people, humans, etc—not users. 
2. Write in active voice. (For example: "You can make a button by..." instead of "buttons are created by...")
3. Don't Repeat Yourself. Link to other docs instead of explaining the same thing twice.
4. Person-first language unless a community in general has expressed a different preference. (For example, "people with ADHD" vs "Autistic individuals")

**Comment by HLeithner** [comment]
just for info the footer gets replaced by the joomla cdn footer and is not part of the documentation.

**Pull request merged**
