### PR TITLE
Update basic-module.md

### PR DESCRIPTION
**Pull request by marcorensch**
Wrote the most simple example for the new structure and gave some hints about the helper and additional Models

### CODE REVIEW

**Comment by robbiejackson** [comment]
Hi Marco, I appreciate the effort of contributing to the documentation but I'm actual working on the module tutorial at the moment. See pull request 261.

**Comment by marcorensch** [comment]
Hi Robbie oh... my fault, I should have checked that first...

**Comment by robbiejackson** [comment]
I haven't finished the tutorial series yet and will be including steps on the service provider file as well as on ajax and update server. 

But there are lots of other documents to update for recent Joomla versions if you're keen, eg several at https://docs.joomla.org/API_Guides.

**Comment by HLeithner** [comment]
/review
--pr_reviewer.extra_instructions="
In the `possible issues` section, emphasize the following:
- Is the code logic efficient?
- 
"
--pr_reviewer.inline_code_comments=false

**Comment by robbiejackson** [comment]
Yes, I think this can coexist with the tutorial. I'm going to try to change it (first time doing that!) and then merge it.

**Comment by robbiejackson** [comment]
Merged as https://github.com/joomla/Manual/pull/289
Thanks Marco!

**Pull request closed without merging**
