### PR TITLE
Chapter about removed db view properties

### PR DESCRIPTION
**Pull request by laoneo**
https://github.com/joomla/joomla-cms/pull/42962

### CODE REVIEW

**Comment by wilsonge** [comment]
We probably also need to document the SQL queries required for 3PD's to migrate away from null date to actual null

**Comment by laoneo** [comment]
But not in the migration document to 6.0. This should be another pr.

**Comment by HLeithner** [comment]
it would be awesome if someone finds the time to move the 3-4 migration from docs to the manual.

**Comment by wilsonge** [comment]
PR is merged so if we fix conflicts here we can merge this too

**Comment by HLeithner** [comment]
merged

**Comment by HLeithner** [comment]
thx

**Pull request merged**
