### PR TITLE
Include en-GB styleguide

### PR DESCRIPTION
**Pull request by brianteeman**
Copies the content from https://github.com/joomla/user-interface-text 

Changed to support Docusaurus - otherwise committed without change.

When merged then https://github.com/joomla/user-interface-text  can be archived and the broken link on developer.joomla.org can be resolved https://github.com/joomla/joomla-websites/issues/1883

### CODE REVIEW

**Comment by HLeithner** [comment]
Thanks

**Comment by HLeithner** [comment]
@brianteeman did you set the file name of references to zreference because of the ordering?

**Comment by brianteeman** [comment]
Yes. If there is another way to do that....

**Comment by HLeithner** [comment]
ok no problem, didn't noticed it earlier only while adding the redirects. I fixed it in commit https://github.com/joomla/Manual/commit/ad7db952de304996b226ad0d54151c244da3343e

**Comment by brianteeman** [comment]
i guess I should have rtfm first

**Pull request merged**
