### PR TITLE
some more corrections of code to get Document

### PR DESCRIPTION
**Pull request by robbiejackson**
Half the changes from $app->getDocument() to $this->app->getDocument() were missed.

This fixes the other ones.

### CODE REVIEW

**Comment by Fedik** [comment]
oh, hold on :smile:
Sorry, I did not seen it previously.

I think it is a mistake in tutorial, the `$this` context should not be available in the tmpl/default.php of the module.
As it is by default for other modules in Joomla. @HLeithner can you confirm or I am missing something?

I see the tutorial uses a custom Dispatcher instead of [`AbstractModuleDispatcher` ](https://github.com/joomla/joomla-cms/blob/912c352df4d72b7e3a58fb1b59b9b05de24ef48d/libraries/src/Dispatcher/AbstractModuleDispatcher.php#L26)or existing `Dispatcher` for module. That where the error comes from.
Iis it was deliberate decision or by accident?

This class do module rendering in the "isolated context" using static function https://github.com/joomla/joomla-cms/blob/912c352df4d72b7e3a58fb1b59b9b05de24ef48d/libraries/src/Dispatcher/AbstractModuleDispatcher.php#L70-L71

**Comment by robbiejackson** [comment]
@Fedik I believe that the tmpl file runs with the context of the View class display() function, so that whatever variables are available there are available within the tmpl file.

It doesn't use AbstractModuleDispatcher until step 10 of the tutorial. That's because I wanted to build up the concepts gradually, and AbstractModuleDispatcher is to complicated to use from the start of the tutorial. 

Probably the error of using `$app` originally came from having AbstractModuleDispatcher used.

**Comment by Fedik** [comment]
>  I believe that the tmpl file runs with the context of the View 

That is true for component views. 
However our core modules are different, historicaly they without `$this` context, and with `$app`.

I not sure if there any plan to change it, I just want to avoid confusion like: core modules looks like "this", and tutorials say "that".

> It doesn't use AbstractModuleDispatcher until step 10 of the tutorial. 

Maybe it make sense to copy that rendering function in to the earlier step?

**Comment by robbiejackson** [comment]
Yes, sorry, in this module code the tmpl file runs within the context of the Dispatcher::dispatch() function, so that is why `$this` is available.

I know that AbstractModuleDispatcher loads it without the context, and that many core modules use this class, but that doesn't mean that extension developers must, or even should, use it. Certainly it's quite complex to get your head around, which is one reason why it's left till step 10. 

In this PR all I'm doing is addressing issue #336 and correcting the text and aligning it with the code in the manual-examples repo. On my last attempt I missed a number of corrections, so this addresses the remainder. I'm not looking to make any changes to the structure of the tutorial series.

**Comment by Fedik** [comment]
All good, I was commenting in general about `$this` in module.

The PR is good for what it is.

**Comment by HLeithner** [comment]
>  or even should,

at least that point I would disagree, extensions developer should use it.

anyway another small thin I found in step 3 
there is the following line
```
        if ($user->id !== 0)  // found a logged-on user
```
it would be better to use the api
```
        if ($user->guest)  // found a logged-on user
```
(of course change the logic of the if) or better use early return (in this case simple removing the else block). Else is normally never needed. But in this case just so simplify the example.

**Comment by robbiejackson** [comment]
@HLeithner I like your suggestion, but I'll leave it out of this PR as it would involve changing the code in all the steps on the other repo as well as testing and explaining it all, and I'm not sure when I'll get time over the next few days. 

I'll bear it in mind next time I'm updating the code. (Or if someone else wants to do it ... ;-))

**Pull request merged**
