### PR TITLE
Docs for Joomla Dialog (popup) script

### PR DESCRIPTION
**Pull request by Fedik**
Docs for PR https://github.com/joomla/joomla-cms/pull/40150
Can be merged only after that PR is merged.

### CODE REVIEW

**Comment by HLeithner** [comment]
Maybe we should create a new section for webcomponents?

**Comment by Fedik** [comment]
I not sure, I think maybe better keep it "by function" instead of "by type".
In future we can have some info for core.js, validation.js, maybe some other js.

I want to keep it simple, in the end it still javascript :)
The section can be added in separated PR, if need.

**Comment by Fedik** [comment]
So the links does not works, because the build use `/versioned_docs/version-4.3` for build not `/docs`, 
Cannot find where it is configured.

**Comment by Fedik** [comment]
Hm, if we use absolute, then it should be without `.md` or it will be just broken, no?

**Comment by HLeithner** [comment]
yes you are right .md is wrong...

**Comment by m4dprodlev** [comment]
<?php $wa->useScript('joomla.dialog'); ?>

**Pull request merged**
