### PR TITLE
Added Docs for git in git.md file

### PR DESCRIPTION
**Pull request by rabahalishah**
Wrote documentation for git and provided the step by step procedure from fork a repo to make a pull request.

### CODE REVIEW

**Comment by rabahalishah** [comment]
Made my first contribution. I hope this would be helpful.

**Comment by HLeithner** [comment]
Thanks for your work but it's for the 4.3 Version only thats the wrong files, please edit only the files in the /docs folder. Thanks

**Comment by rabahalishah** [comment]
@HLeithner okay let me add docs to the correct file.

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
