### PR TITLE
Webservices API json response tutorial

### PR DESCRIPTION
**Pull request by carlitorweb**
Joomla by default will return a [JSON API](https://jsonapi.org/) Responses when requested with an `Accept: application/json ` header as well as with the specific JSON API header. This tutorial help build a different response, in this case, a JSON response.

### The goals
-   Get a JSON response from the Joomla API
-   Create the necessary webservices plugin and the API part of the component
-   Use a module params for model the data we will send in the API response

### CODE REVIEW

**Comment by carlitorweb** [comment]
> 2 things, first we save the assets in a "assets" subdirectory relative to the markdown file.
second could you please polish the object with correct intention, don't know if type php makes a better highlight instead of log

Done.

> PR looks promising.
Thank you, glad to hear that.

**Comment by HLeithner** [comment]
you have a TODO about https://github.com/joomla/joomla-cms/pull/39498 which is already merged. so you can remove this function completly because the documentation is for j4.3 please

**Comment by carlitorweb** [comment]
I was thinking that maybe someone apply this for 4.2, then will not work as expected. Is not better wait to 4.3 arrive, and then update the doc? If not, I delete it not problem. If that is the case, should I highlight somewhere this tutorial is for 4.3+ ?

Also, let me kown any other changes I need do do the tutorial, I will glad to do it.

**Comment by carlitorweb** [comment]
My bad, the merged of that PR was in 4.2-dev branch...not sure why I saw 4.3

**Comment by HLeithner** [comment]
In the top left corner you see that this documentation targets version 4.3 
image

We don't have and plan a 4.2 version.

but good that you found out that it already works in 4.2 ;-)

**Comment by HLeithner** [comment]
Hi I merged the webservices pr #41 which can be found here https://manual.joomla.org/docs/general-concept/webservices/ can you please restructure your pr in a way that it fits together?

**Comment by carlitorweb** [comment]
@HLeithner both articles are related, but in different layers. #41 is how you build the request for consume the API. This tutorial is how you build the response. 

As far I see, for connect both is just need #41 write a small section of how add the Header: application/json and point to this article for how should be structure the response for get the json. 

Let me kown if anything anyway, maybe I understood wrong what do you meant

**Comment by HLeithner** [comment]
hopefully @bembelimen can help here, I'm only for technical issues with docusaurus here

**Comment by carlitorweb** [comment]
In my opinion, you can merge this tutorial as is now. All used here is straight forward really. The only significan change is the View part, but is easy to check (in case the tutorial is holded because need be checked first by someone)

**Comment by HLeithner** [comment]
@carlitorweb as said it's not longer in my responsibility

In my opinion "[Web Services API](http://pr-74.manual.joomlacode.org/docs/web-services-api/)" has nothing to do on the first level document but if you find someone who want's to manage the documentation please contact @bembelimen

**Comment by HLeithner** [comment]
Can be moved if it doesn't here, thanks

**Pull request merged**
