### PR TITLE
Converted from existing J4 Document

### PR DESCRIPTION
**Pull request by ceford**
This is just to test to see how to do conversion of an existing tutorial goes using pandoc.

### CODE REVIEW

**Comment by HLeithner** [comment]
sadly we don't have pr based previews yet but I'm working on this.

Do you have a screenshot how it looks like?

**Comment by ceford** [comment]
The original document is here: https://docs.joomla.org/J4.x:Dependency_Injection_in_Joomla_4

I would not normally include a whole document screenshot, but as this is a first time...

One thing I noticed is that in-line quotes have become block quotes.

image

**Comment by bembelimen** [comment]
> This is just to test to see how to do conversion of an existing tutorial goes using pandoc.

Thanks @ceford for your PR,

Is it for merging or just testing?

**Comment by ceford** [comment]
> > This is just to test to see how to do conversion of an existing tutorial goes using pandoc.
> 
> Thanks @ceford for your PR,
> 
> Is it for merging or just testing?

I think it could be merged as an example for others to look at. I did a previous small edit - just a typo/grammar fix and was surprised and pleased that the **Edit this page** link seemed to do most of the pull request stuff for me. That made me bold enough to try something bigger. I was wondering how we would test contributions. I was also wondering about how/where to handle images. I think we need some sort of _procedure guide_. I would be happy to do whatever you suggest.

**Comment by ceford** [comment]
I have notice that one link points to a Jdocs document with no domain - so is broken. Some rewriting needed?

**Comment by ceford** [comment]
I fixed the broken link and removed the ToDo block so this document looks _finished_.

**Comment by bembelimen** [comment]
Thanks

**Pull request merged**
