### PR TITLE
Adding deprecations for com_search-specific Language methods

### PR DESCRIPTION
**Pull request by Hackwar**
This is the corresponding PR to https://github.com/joomla/joomla-cms/pull/40727

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks!

**Comment by HLeithner** [comment]
That was the wrong file, the deprecation has been introduced in 4.4 not in 5.0

**Comment by laoneo** [comment]
So it must be from 4.3 to 4.4?

**Comment by HLeithner** [comment]
yes, the files describes the changes between Version 4.3 and 4.4, now it's in the file between 4.4 and 5.0

**Comment by laoneo** [comment]
Here we go https://github.com/joomla/Manual/pull/125. Thanks for the hint.

**Pull request merged**
