### PR TITLE
Documentation for custom error pages PR40597

### PR DESCRIPTION
**Pull request by brianteeman**

### CODE REVIEW

**Comment by HLeithner** [comment]
are the images free?

**Comment by brianteeman** [comment]
oh - good point. I have a licence for them but I will change them to something 100% free and save the source in the filename

**Comment by brianteeman** [comment]
images  have been changed with images from pexels.com - the commit message has the source file name. Licence is https://www.pexels.com/license/

**Comment by brianteeman** [comment]
thx

**Pull request merged**
