### PR TITLE
Add deprecation note for joomla/joomla-cms#42090

### PR DESCRIPTION
**Pull request by heelc29**

### CODE REVIEW

**Comment by HLeithner** [comment]
@heelc29 can you resolve the conflict then it can be merged since reference pr has been merged

**Comment by heelc29** [comment]
> @heelc29 can you resolve the conflict then it can be merged since reference pr has been merged

Done.

**Comment by heelc29** [comment]
@HLeithner RTC

**Comment by HLeithner** [comment]
thx

**Pull request merged**
