### PR TITLE
Module cache deprecation

### PR DESCRIPTION
**Pull request by laoneo**

### CODE REVIEW

**Comment by HLeithner** [comment]
Hi Allon,

you did make 2 mistakes.
1. as already said, please don't make changes to the `migration/44-50` directory in the `main` branch
2. in this case the deprecation is added to Joomla 4.4 and needs to to be added to the `migration/43-44` entry

**Comment by laoneo** [comment]
To which branch then?

**Comment by HLeithner** [comment]
> To which branch then?

for this pr it's the wrong directory but the correct branch.

for 5.0 changes its the 5.0 branch

**Comment by laoneo** [comment]
Moved the to the 4.3 file

**Comment by HLeithner** [comment]
thanks.

Is the wording of the files too complicated or confusing?

**Comment by laoneo** [comment]
Personally I would expect a file with the name 4.4 which contains all deprecation which are done in 4.4. Where and how this file is then displayed is another story. It is all about the perspective, now it is the perspective for the end developer who reads it, I have the perspective of the developer who does it. But you can leave it as it is, no problem.

**Pull request closed without merging**
