### PR TITLE
Custom Script - for version 4.4 only

### PR DESCRIPTION
**Pull request by robbiejackson**

### CODE REVIEW

**Comment by HLeithner** [comment]
do we already have a section about how to write a console command plugin?

because we don't like to promote this type of console scripts or direct entry points, so adding at least a :::danger box on each relevant page would be appreciated and how a link to how to write a plugin for this use case.

**Comment by robbiejackson** [comment]
Happy to add a box on each page - maybe warning would be more appropriate than danger.

I'm preparing the documentation for plugins now and have got a sample console plugin ready to include there. However, the issue is that console plugins need to be run from the command line, and it's often not appropriate to give consumers of such scripts access to the command line.

**Comment by HLeithner** [comment]
A cli application has a different use case then something called from the web.

For webcall create a component or an plugin/module with an ajax endpoint.

**Comment by robbiejackson** [comment]
Here are a couple of use cases I've thought of:

A college has an online enrolment site built on Joomla and a lecturer wants to find how many students are enrolled in his course. He can just navigate to a custom script (on an address perhaps protected by the college firewall) to get the answer.

Or an organisation has installed an extension to allow people to book against events. And immediately before an event someone wants to know how many chairs to put out.

Or as a temporary solution, where managers want to be able to keep up-to-date with stats on a volatile situation which is being managed via a Joomla site. 

If there's a basic script there, eg just doing a sql query, then changes can be done in minutes and the solution immediately deployed.

Sure, you can do these sorts of things via Joomla components, but they take a lot longer to develop, and are much more costly. 

Requests for help with writing such scripts come up in forums fairly regularly, so there are people wanting to use this.

**Comment by HLeithner** [comment]
It's not that we don't allow it or don't want to document it at all, just to notice that this not the preferred why.

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
